"""Initial

Revision ID: fa90629a5384
Revises: c2654526e7d6
Create Date: 2021-04-07 19:11:46.738343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa90629a5384'
down_revision = 'c2654526e7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
